### ISSUE TITLE
How are the wavefield binary files structured? 

### ISSUE THREAD

**Issue by firstkingofrome** [geodynamics/specfem2d#1141]
Hello I was wondering where I could find more information about how the binary wavefield files are structured. I would like to use these (instead of the jpeg outputs) so that I can add my own scales to my images. Where can I find a description of how this file is layed out (this does not seem to be included in the manual),it does not look like the actual wavefiled files have any kind of header at all, are these simply assumed to be little endian floating point numbers? I would also like to know what the wavefield_grid_for_dumps.bin file contains. Thank You, I appreciate any assistance in figuring this structure out.

The zip file I have attached includes a sample wavefiled_grid_for_dumps file and a binary wave field file.

Thank You, I appreciate any assitance in figuring this out.

[mystery_binaries.zip](https://github.com/geodynamics/specfem2d/files/7937489/mystery_binaries.zip)

**Comment by EtienneBachmann** [comment]
Hi, the binary wavefield files contain the wavefield snapshot on the global integration grid, of size NGLOB. You can get this value by looking at the specfem output or looking the size of the file and dividing by four. The endianess is the one of your machine. Because this is an unstructured mesh, you need the 2 coordinates of each point, given in the wavefield_grid_for_dumps.bin file. The contiguous in memory pair of float "N" will give you the coordinates of the point "N" in the wavefield files. 
Hope this helps,

Etienne

**Comment by firstkingofrome** [comment]
Thank You, that is helpful
