### ISSUE TITLE
Weird results from example Rayleigh_wave_with_crack

### ISSUE THREAD

**Issue by wanglongqi** [geodynamics/specfem2d#290]
I am new to this software. I start running examples in the `EXAMPLES` folder. I find following weird behavior of the program.

In `Rayleigh_wave_with_crack` example, if you change `nproc   = 4 `, the outputs are different with `nproc   = 1`. 

For `np=1`, I get following output: https://youtu.be/ztzRk1ccUpc ,
For `np=4`, I get following output: http://youtu.be/wv5ekGsURaQ .

I think the results should keep the same for different np. Do I make a mistake here?

**Comment by komatits** [comment]
That example is the only one that cannot run in parallel (i.e. with 
MPI), because I use a trick inside the code to include a mathematical 
crack. Thus always run it with nproc = 1. I'll add a note in the README 
file of that example.

Dimitri.

On 04/17/2015 07:18 AM, WANG Longqi wrote:
> I am new to this software. I start running examples in the |EXAMPLES|
> folder. I find following weird behavior of the program.
>
> In |Rayleigh_wave_with_crack| example, if you change |nproc = 4|, the
> outputs are different with |nproc = 1|.
>
> For |np=1|, I get following output: https://youtu.be/ztzRk1ccUpc ,
> For |np=4|, I get following output: http://youtu.be/wv5ekGsURaQ .
>
> I think the results should keep the same for different np. Do I make a
> mistake here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/290>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by wanglongqi** [comment]
@komatits Thanks for your explanation!
